mbaggett@hydra:/scripts$ cat iptables.sh
#!/bin/sh

ipt="/sbin/iptables"
rt="/sbin/route"
ip="/sbin/ip"
rm255="10.25.0.0/24"
rm256="10.255.26.0/24"
rm257="10.25.1.0/24"
rm258="10.25.2.0/24"
rm259="10.25.3.0/24"
rm205="10.25.4.0/24"
rm101="10.25.5.0/24"
rm102="10.25.6.0/24"
rm104="10.25.7.0/24"
nwpub="10.20.1.0/24"

SEC504CTF="ens160"
SEC504LAB="ens192"
SEC560CTF="ens224"
SEC573="ens256"

######## RESTART NETWORKING ########
/usr/sbin/netplan apply

######## IPTABLES ########
## Flush existing rules and set defaults - DON'T MODIFY
$ipt -F
$ip rule flush
$ip rule add from all lookup main pref 32766


####### SOURCE ROUTING #######
## CREATE BEFORE ADDING ROUTES - UNCOMMENT TO USE
## LOOK FOR LINE WITH ROOM, CHANGE "TABLE" TO DESIRED CLASS e.g 573 to 504
## 5041=504 lab week 504=504 CTF  5042=504.MIL 5043=504 ctf in a 2nd class
## 560=560 CTF
## 567=573 and 561
## Room 256 is the instructor room
###BEGIN AUTOGENERATED RULES BY HYDRACLI.PY###
$ip rule add from $rm101 table main
$ip rule add from $rm102 table main
$ip rule add from $rm104 table main
$ip rule add from $rm205 table main
$ip rule add from $rm255 table 573
$ip rule add from $rm256 table main
$ip rule add from $rm257 table main
$ip rule add from $rm258 table main
$ip rule add from $rm259 table main
###END AUTOGENERATED RULES BY HYDRACLI.PY###

####### TABLE 5041 ##### SEC504 CTF ROUTES #######
$ip route add 10.10.10.9 dev $SEC504CTF table 504
$ip route add 10.10.10.15 dev $SEC504CTF table 504
$ip route add 10.10.10.35 dev $SEC504CTF table 504
$ip route add 10.10.10.45 dev $SEC504CTF table 504
$ip route add default via 10.20.1.254 dev ens33 table 504

####### TABLE 504 ##### SEC504 LABS ROUTES #######
$ip route add 10.10.10.9 dev $SEC504LAB table 5041
$ip route add 10.10.10.15 dev $SEC504LAB table 5041
$ip route add 10.10.10.30 dev $SEC504LAB table 5041
$ip route add default via 10.20.1.254 dev ens33 table 5041

####### TABLE 5601 ##### SEC560 CTF ROUTES #######
$ip route add 10.10.1.1 dev $SEC560CTF table 560
$ip route add 10.10.1.254 dev $SEC560CTF table 560
$ip route add 10.11.11.0/24 via 10.10.1.1 dev $SEC560CTF table 560
$ip route add default via 10.20.1.254 dev ens33 table 560

####### TABLE 560 ##### SEC560 LABS ROUTES #######
$ip route add 10.10.10.10 dev $SEC560CTF table 560
$ip route add 10.10.10.20 dev $SEC560CTF table 560
$ip route add 10.10.10.50 dev $SEC560CTF table 560
$ip route add 10.10.10.60 dev $SEC560CTF table 560
$ip route add default via 10.20.1.254 dev ens33 table 560

####### TABLE 561 ##### SEC561 ROUTES #######
#$ip route add 10.10.10.4 dev $SEC561 table 561
#$ip route add 10.10.10.10 dev $SEC561 table 561
#$ip route add 10.10.10.11 dev $SEC561 table 561
#$ip route add 10.10.10.20 dev $SEC561 table 561
#$ip route add default via 10.20.1.254 dev ens33 table 561

####### TABLE 573 ##### SEC573 ROUTES #######
$ip route add 10.10.10.10 dev $SEC573 table 573
$ip route add 10.10.10.11 dev $SEC573 table 573
$ip route add 10.10.10.20 dev $SEC573 table 573
$ip route add 10.10.10.30 dev $SEC573 table 573
$ip route add default via 10.20.1.254 dev ens33 table 573

####### TABLE 5042 ##### SEC504.mil LABS ROUTES #######
#$ip route add 10.10.10.10 dev $SEC560LAB table 5042
#$ip route add 10.10.10.20 dev $SEC560LAB table 5042
#$ip route add 10.10.10.50 dev $SEC560LAB table 5042
#$ip route add 10.10.10.60 dev $SEC560LAB table 5042
#$ip route add 10.10.10.9 dev $SEC504LAB table 5042
#$ip route add 10.10.10.15 dev $SEC504LAB table 5042
#$ip route add 10.10.10.30 dev $SEC504LAB table 5042
#$ip route add default via 10.20.1.254 dev ens33 table 5042

####### TABLE 5043 ##### SEC504 CTF2  ROUTES #######
#$ip route add 10.10.10.9 dev $SEC504CTF2 table 5043
#$ip route add 10.10.10.15 dev $SEC504CTF2 table 5043
#$ip route add 10.10.10.35 dev $SEC504CTF2 table 5043
#$ip route add 10.10.10.45 dev $SEC504CTF2 table 5043
#$ip route add default via 10.20.1.254 dev ens33 table 5043

####### TABLE 567 ##### SEC561 and SEC 573 ROUTES #######
#$ip route add 10.10.10.4 dev $SEC561 table 567
#$ip route add 10.10.10.10 dev $SEC561 table 567
#$ip route add 10.10.10.11 dev $SEC561 table 567
#$ip route add 10.10.10.20 dev $SEC561 table 567
#$ip route add 10.10.10.110 dev $SEC573 table 567
#$ip route add 10.10.10.120 dev $SEC573 table 567
#$ip route add 10.10.10.130 dev $SEC573 table 567

